import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import {Roboto} from "next/font/google";
import "bootstrap-icons/font/bootstrap-icons.css";

const roboto= Roboto({subsets:["latin"],weight:["400","700"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
